import 'package:equatable/equatable.dart';

class SurahModel extends Equatable {
  final int id;
  final String name;
  final int versesCount;
  final String revelationPlace;

  const SurahModel({
    required this.id,
    required this.name,
    required this.versesCount,
    required this.revelationPlace,
  });

  @override
  List<Object?> get props => [id];
}

// ignore: non_constant_identifier_names
final List<SurahModel> SUR = [
  SurahModel(id: 1, name: 'الفاتحة', versesCount: 7, revelationPlace: 'makkah'),
  SurahModel(
    id: 2,
    name: 'البقرة',
    versesCount: 286,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 3,
    name: 'آل عمران',
    versesCount: 200,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 4,
    name: 'النساء',
    versesCount: 176,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 5,
    name: 'المائدة',
    versesCount: 120,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 6,
    name: 'الأنعام',
    versesCount: 165,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 7,
    name: 'الأعراف',
    versesCount: 206,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 8,
    name: 'الأنفال',
    versesCount: 75,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 9,
    name: 'التوبة',
    versesCount: 129,
    revelationPlace: 'madinah',
  ),
  SurahModel(id: 10, name: 'يونس', versesCount: 109, revelationPlace: 'makkah'),
  SurahModel(id: 11, name: 'هود', versesCount: 123, revelationPlace: 'makkah'),
  SurahModel(id: 12, name: 'يوسف', versesCount: 111, revelationPlace: 'makkah'),
  SurahModel(
    id: 13,
    name: 'الرعد',
    versesCount: 43,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 14,
    name: 'ابراهيم',
    versesCount: 52,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 15, name: 'الحجر', versesCount: 99, revelationPlace: 'makkah'),
  SurahModel(
    id: 16,
    name: 'النحل',
    versesCount: 128,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 17,
    name: 'الإسراء',
    versesCount: 111,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 18,
    name: 'الكهف',
    versesCount: 110,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 19, name: 'مريم', versesCount: 98, revelationPlace: 'makkah'),
  SurahModel(id: 20, name: 'طه', versesCount: 135, revelationPlace: 'makkah'),
  SurahModel(
    id: 21,
    name: 'الأنبياء',
    versesCount: 112,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 22, name: 'الحج', versesCount: 78, revelationPlace: 'madinah'),
  SurahModel(
    id: 23,
    name: 'المؤمنون',
    versesCount: 118,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 24,
    name: 'النور',
    versesCount: 64,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 25,
    name: 'الفرقان',
    versesCount: 77,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 26,
    name: 'الشعراء',
    versesCount: 227,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 27, name: 'النمل', versesCount: 93, revelationPlace: 'makkah'),
  SurahModel(id: 28, name: 'القصص', versesCount: 88, revelationPlace: 'makkah'),
  SurahModel(
    id: 29,
    name: 'العنكبوت',
    versesCount: 69,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 30, name: 'الروم', versesCount: 60, revelationPlace: 'makkah'),
  SurahModel(id: 31, name: 'لقمان', versesCount: 34, revelationPlace: 'makkah'),
  SurahModel(
    id: 32,
    name: 'السجدة',
    versesCount: 30,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 33,
    name: 'الأحزاب',
    versesCount: 73,
    revelationPlace: 'madinah',
  ),
  SurahModel(id: 34, name: 'سبإ', versesCount: 54, revelationPlace: 'makkah'),
  SurahModel(id: 35, name: 'فاطر', versesCount: 45, revelationPlace: 'makkah'),
  SurahModel(id: 36, name: 'يس', versesCount: 83, revelationPlace: 'makkah'),
  SurahModel(
    id: 37,
    name: 'الصافات',
    versesCount: 182,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 38, name: 'ص', versesCount: 88, revelationPlace: 'makkah'),
  SurahModel(id: 39, name: 'الزمر', versesCount: 75, revelationPlace: 'makkah'),
  SurahModel(id: 40, name: 'غافر', versesCount: 85, revelationPlace: 'makkah'),
  SurahModel(id: 41, name: 'فصلت', versesCount: 54, revelationPlace: 'makkah'),
  SurahModel(
    id: 42,
    name: 'الشورى',
    versesCount: 53,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 43,
    name: 'الزخرف',
    versesCount: 89,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 44,
    name: 'الدخان',
    versesCount: 59,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 45,
    name: 'الجاثية',
    versesCount: 37,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 46,
    name: 'الأحقاف',
    versesCount: 35,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 47, name: 'محمد', versesCount: 38, revelationPlace: 'madinah'),
  SurahModel(
    id: 48,
    name: 'الفتح',
    versesCount: 29,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 49,
    name: 'الحجرات',
    versesCount: 18,
    revelationPlace: 'madinah',
  ),
  SurahModel(id: 50, name: 'ق', versesCount: 45, revelationPlace: 'makkah'),
  SurahModel(
    id: 51,
    name: 'الذاريات',
    versesCount: 60,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 52, name: 'الطور', versesCount: 49, revelationPlace: 'makkah'),
  SurahModel(id: 53, name: 'النجم', versesCount: 62, revelationPlace: 'makkah'),
  SurahModel(id: 54, name: 'القمر', versesCount: 55, revelationPlace: 'makkah'),
  SurahModel(
    id: 55,
    name: 'الرحمن',
    versesCount: 78,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 56,
    name: 'الواقعة',
    versesCount: 96,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 57,
    name: 'الحديد',
    versesCount: 29,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 58,
    name: 'المجادلة',
    versesCount: 22,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 59,
    name: 'الحشر',
    versesCount: 24,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 60,
    name: 'الممتحنة',
    versesCount: 13,
    revelationPlace: 'madinah',
  ),
  SurahModel(id: 61, name: 'الصف', versesCount: 14, revelationPlace: 'madinah'),
  SurahModel(
    id: 62,
    name: 'الجمعة',
    versesCount: 11,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 63,
    name: 'المنافقون',
    versesCount: 11,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 64,
    name: 'التغابن',
    versesCount: 18,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 65,
    name: 'الطلاق',
    versesCount: 12,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 66,
    name: 'التحريم',
    versesCount: 12,
    revelationPlace: 'madinah',
  ),
  SurahModel(id: 67, name: 'الملك', versesCount: 30, revelationPlace: 'makkah'),
  SurahModel(id: 68, name: 'القلم', versesCount: 52, revelationPlace: 'makkah'),
  SurahModel(
    id: 69,
    name: 'الحاقة',
    versesCount: 52,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 70,
    name: 'المعارج',
    versesCount: 44,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 71, name: 'نوح', versesCount: 28, revelationPlace: 'makkah'),
  SurahModel(id: 72, name: 'الجن', versesCount: 28, revelationPlace: 'makkah'),
  SurahModel(
    id: 73,
    name: 'المزمل',
    versesCount: 20,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 74,
    name: 'المدثر',
    versesCount: 56,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 75,
    name: 'القيامة',
    versesCount: 40,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 76,
    name: 'الانسان',
    versesCount: 31,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 77,
    name: 'المرسلات',
    versesCount: 50,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 78, name: 'النبإ', versesCount: 40, revelationPlace: 'makkah'),
  SurahModel(
    id: 79,
    name: 'النازعات',
    versesCount: 46,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 80, name: 'عبس', versesCount: 42, revelationPlace: 'makkah'),
  SurahModel(
    id: 81,
    name: 'التكوير',
    versesCount: 29,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 82,
    name: 'الإنفطار',
    versesCount: 19,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 83,
    name: 'المطففين',
    versesCount: 36,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 84,
    name: 'الإنشقاق',
    versesCount: 25,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 85,
    name: 'البروج',
    versesCount: 22,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 86,
    name: 'الطارق',
    versesCount: 17,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 87,
    name: 'الأعلى',
    versesCount: 19,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 88,
    name: 'الغاشية',
    versesCount: 26,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 89, name: 'الفجر', versesCount: 30, revelationPlace: 'makkah'),
  SurahModel(id: 90, name: 'البلد', versesCount: 20, revelationPlace: 'makkah'),
  SurahModel(id: 91, name: 'الشمس', versesCount: 15, revelationPlace: 'makkah'),
  SurahModel(id: 92, name: 'الليل', versesCount: 21, revelationPlace: 'makkah'),
  SurahModel(id: 93, name: 'الضحى', versesCount: 11, revelationPlace: 'makkah'),
  SurahModel(id: 94, name: 'الشرح', versesCount: 8, revelationPlace: 'makkah'),
  SurahModel(id: 95, name: 'التين', versesCount: 8, revelationPlace: 'makkah'),
  SurahModel(id: 96, name: 'العلق', versesCount: 19, revelationPlace: 'makkah'),
  SurahModel(id: 97, name: 'القدر', versesCount: 5, revelationPlace: 'makkah'),
  SurahModel(
    id: 98,
    name: 'البينة',
    versesCount: 8,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 99,
    name: 'الزلزلة',
    versesCount: 8,
    revelationPlace: 'madinah',
  ),
  SurahModel(
    id: 100,
    name: 'العاديات',
    versesCount: 11,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 101,
    name: 'القارعة',
    versesCount: 11,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 102,
    name: 'التكاثر',
    versesCount: 8,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 103, name: 'العصر', versesCount: 3, revelationPlace: 'makkah'),
  SurahModel(
    id: 104,
    name: 'الهمزة',
    versesCount: 9,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 105, name: 'الفيل', versesCount: 5, revelationPlace: 'makkah'),
  SurahModel(id: 106, name: 'قريش', versesCount: 4, revelationPlace: 'makkah'),
  SurahModel(
    id: 107,
    name: 'الماعون',
    versesCount: 7,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 108,
    name: 'الكوثر',
    versesCount: 3,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 109,
    name: 'الكافرون',
    versesCount: 6,
    revelationPlace: 'makkah',
  ),
  SurahModel(
    id: 110,
    name: 'النصر',
    versesCount: 3,
    revelationPlace: 'madinah',
  ),
  SurahModel(id: 111, name: 'المسد', versesCount: 5, revelationPlace: 'makkah'),
  SurahModel(
    id: 112,
    name: 'الإخلاص',
    versesCount: 4,
    revelationPlace: 'makkah',
  ),
  SurahModel(id: 113, name: 'الفلق', versesCount: 5, revelationPlace: 'makkah'),
  SurahModel(id: 114, name: 'الناس', versesCount: 6, revelationPlace: 'makkah'),
];
